<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2024, WSO2 LLC. (http://www.wso2.org).
  ~
  ~ WSO2 LLC. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<!DOCTYPE assembly [
        <!ELEMENT assembly (id|formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes|outputFileNameMapping)*>
        <!ELEMENT outputFileNameMapping (#PCDATA)>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|destName|filtered)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        ]>
<assembly>
    <id>connector-tool-bin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory>target/connector-generator</directory>
            <outputDirectory>connector-generator</outputDirectory>
<!--            <excludes>-->
<!--                <exclude>**/diagnostics</exclude>-->
<!--                <exclude>**/diagnostics.bat</exclude>-->
<!--                <exclude>**/lib/annotations*</exclude>-->
<!--                <exclude>**/lib/antlr-runtime*</exclude>-->
<!--                <exclude>**/lib/antlr4-4*</exclude>-->
<!--                <exclude>**/lib/icu4j*</exclude>-->
<!--                <exclude>**/lib/javax.json*</exclude>-->
<!--                <exclude>**/lib/jsr305*</exclude>-->
<!--                <exclude>**/lib/kotlin*</exclude>-->
<!--                <exclude>**/lib/org.abego.treelayout.core*</exclude>-->
<!--                <exclude>**/lib/ST4*</exclude>-->
<!--            </excludes>-->
            <fileMode>644</fileMode>
        </fileSet>
        <fileSet>
            <directory>lib</directory>
            <outputDirectory>connector-generator/lib</outputDirectory>
            <fileMode>644</fileMode>
        </fileSet>
    </fileSets>

    <files>
        <file>
            <source>target/connector-generator/bin/generator</source>
            <outputDirectory>connector-generator/bin</outputDirectory>
            <destName>generator</destName>
            <fileMode>744</fileMode>
        </file>
    </files>

</assembly>